### ISSUE TITLE
Pip install doesn't include encode_motifs.txt.gz

### ISSUE THREAD

**Issue by rbharath** [kundajelab/simdna#6]
```
======================================================================
ERROR: Failure: IOError ([Errno 2] No such file or directory: '/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/simdna/resources/encode_motifs.txt.gz')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/deepchem/deepchem/deepchem/__init__.py", line 12, in <module>
    import deepchem.hyper
  File "/home/travis/build/deepchem/deepchem/deepchem/hyper/__init__.py", line 2, in <module>
    from deepchem.hyper.gaussian_process import GaussianProcessHyperparamOpt
  File "/home/travis/build/deepchem/deepchem/deepchem/hyper/gaussian_process.py", line 13, in <module>
    from deepchem.molnet.run_benchmark_models import benchmark_classification, benchmark_regression
  File "/home/travis/build/deepchem/deepchem/deepchem/molnet/__init__.py", line 29, in <module>
    from deepchem.molnet.dnasim import simulate_motif_density_localization
  File "/home/travis/build/deepchem/deepchem/deepchem/molnet/dnasim.py", line 25, in <module>
    simdna.ENCODE_MOTIFS_PATH, pseudocountProb=0.001)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/simdna/synthetic/loadedmotifs.py", line 60, in __init__
    fileHandle = util.get_file_handle(fileName)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/simdna/util.py", line 69, in get_file_handle
    return gzip.open(filename,mode)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/simdna/resources/encode_motifs.txt.gz'
```
CC @lilleswing 

It might be good to host the gzip file in the cloud and download as needed to avoid issues. (This is the strategy that `dc.molnet` takes). Would be happy to host this gzip file on the DeepChem S3 bucket if that would be convenient.

**Comment by lilleswing** [comment]
We have to add the file to a MANIFEST file.

**Comment by AvantiShri** [comment]
@lilleswing thank you very much for uploading simdna to pypi. I've made updates since then and am contemplating updating the pypi repo as well, but of course I don't want to have to bother you to manage these updates. Is there a way for you to transfer maintenance of the pypi package to another user? I have an account on pypi (https://pypi.org/user/AvantiShri/)

**Comment by AvantiShri** [comment]
@lilleswing Could you please add me as an owner of the simdna package so that I can continue maintaining it on pypi? It looks like you can transfer ownership by following the instructions outlined in this github thread: https://github.com/pypa/warehouse/issues/1745

**Comment by AvantiShri** [comment]
@lilleswing gentle reminder about sharing ownership of the simdna pypi repo. The only alternative would be for me to create a second simdna pypi package, which I would prefer not to do to avoid creating confusion.

**Comment by AvantiShri** [comment]
@lilleswing can you please add me as a co-owner of the simdna repository? It is becoming an issue and we are contemplating making a separate simdna package to upload different versions.
